export const countries = [
    ['Brazil', 'Brasília'],
    ['Argentina', 'Buenos Aires'],
    ['Chile', 'Santiago'],
    ['Colombia', 'Bogotá'],
    ['Peru', 'Lima'],
    ['Uruguay', 'Montevideo'],
    ['Paraguay', 'Asunción'],
    ['Venezuela', 'Caracas'],
    ['Ecuador', 'Quito'],
    ['Bolivia', 'La Paz'],
    ['Canada', 'Ottawa'],
    ['United States', 'Washington, D.C.'],
    ['Mexico', 'Mexico City'],
    ['France', 'Paris'],
    ['Germany', 'Berlin'],
    ['United Kingdom', 'London'],
    ['Italy', 'Rome'],
    ['Spain', 'Madrid'],
    ['Russia', 'Moscow'],
    ['Portugal', 'Lisbon'],
    ['Belgium', 'Brussels'],
    ['Luxembourg', 'Luxembourg'],
    ['Netherlands', 'Amsterdam'],
    ['Switzerland', 'Bern'],
    ['Denmark', 'Copenhagen'],
    ['Poland', 'Warsaw'],
    ['Belarus', 'Minsk'],
    ['Lithuania', 'Vilnius'],
    ['Latvia', 'Riga'],
    ['Estonia', 'Tallinn'],
    
    ['Egypt', 'Cairo'],
    ['Nigeria', 'Abuja'],
    ['South Africa', 'Cape Town'],
    ['Kenya', 'Nairobi'],
    ['Jamaica', 'Kingston'],
    ['Japan', 'Tokyo'],
    ['China', 'Beijing'],
    ['India', 'New Delhi'],
    ['South Korea', 'Seoul'],
    ['Indonesia', 'Jakarta'],
    ['Thailand', 'Bangkok'],
    ['Vietnam', 'Hanoi'],
    ['Mongolia', 'Ulaanbaatar'],
    ['Afghanistan', 'Kabul'],
    ['Pakistan', 'Islamabad'],
    ['Bangladesh', 'Dhaka'],
    ['Sri Lanka', 'Colombo'],
    ['Nepal', 'Kathmandu'],
    ['Bhutan', 'Thimphu'],
    ['Malaysia', 'Kuala Lumpur'],
    ['Singapore', 'Singapore'],
    ['Philippines', 'Manila'],
    ['Australia', 'Canberra'],
    ['New Zealand', 'Wellington'],
    ['Fiji', 'Suva'],
    ['Panama', 'Panama City'],
    ['Costa Rica', 'San Jose'],
    ['Nicaragua', 'Managua'],
    ['El Salvador', 'San Salvador'],
    ['Honduras', 'Tegucigalpa'],
    ['Guatemala', 'Guatemala City']
]