export const paises = [
    ['Brasil', 'Brasília'],
    ['Argentina', 'Buenos Aires'],
    ['Chile', 'Santiago'],
    ['Colômbia', 'Bogotá'],
    ['Peru', 'Lima'],
    ['Uruguai', 'Montevidéu'],
    ['Paraguai', 'Assunção'],
    ['Venezuela', 'Caracas'],
    ['Equador', 'Quito'],
    ['Bolívia', 'La Paz'],
    ['Canadá', 'Ottawa'],
    ['Estados Unidos', 'Washington, D.C.'],
    ['México', 'Cidade do México'],
    ['França', 'Paris'], 
    ['Alemanha', 'Berlim'],
    ['Reino Unido', 'Londres'],
    ['Itália', 'Roma'],
    ['Espanha', 'Madri'],
    ['Rússia', 'Moscou'],
    ['Portugal', 'Lisboa'],
    ['Belgica', 'Bruxelas'],
    ['Luxemburgo', 'Luxemburgo'],
    ['Holanda', 'Amsterdã'],
    ['Suiça', 'Berna'],
    ['Dinamarca', 'Copenhague'],
    ['Polônia', 'Varsóvia'],
    ['Bielorrússia', 'Minsk'],
    ['Lituânia', 'Vilnius'],
    ['Letônia', 'Rita'],
    ['Estônia', 'Tallinn'],
    
    ['Egito', 'Cairo'],
    ['Nigéria', 'Abuja'],
    ['África do Sul', 'Cidade do Cabo'],
    ['Quênia', 'Nairobi'],
    ['Jamaica', 'Kingston'],
    ['Japão', 'Tóquio'],
    ['China', 'Pequim'],
    ['Índia', 'Nova Delhi'],
    ['Coreia do Sul', 'Seul'],
    ['Indonésia', 'Jacarta'],
    ['Tailândia', 'Bangkok'],
    ['Vietnã', 'Hanói'],
    ['Mongólia', 'Ulaanbaatar'],
    ['Afeganistão', 'Cabul'],
    ['Paquistão', 'Islamabad'],
    ['Bangladesh', 'Daca'],
    ['Sri Lanka', 'Colombo'],
    ['Nepal', 'Katmandu'],
    ['Butão', 'Timbu'],
    ['Malásia', 'Kuala Lumpur'],
    ['Singapura', 'Singapura'],
    ['Filipinas', 'Manila'],
    ['Austrália', 'Camberra'],
    ['Nova Zelândia', 'Wellington'],
    ['Fiji', 'Suva'],
    ['Panamá', 'Cidade do Panamá'],
    ['Costa Rica', 'San José'],
    ['Nicarágua', 'Manágua'],
    ['El Salvador', 'San Salvador'],
    ['Honduras', 'Tegucigalpa'],
    ['Guatemala', 'Cidade da Guatemala'],
];